//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSApplication.ServiceReference1
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.ImageUploader1Soap")]
    public interface ImageUploader1Soap
    {
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/HelloWorld", ReplyAction = "*")]
        ITSApplication.ServiceReference1.HelloWorldResponse HelloWorld(ITSApplication.ServiceReference1.HelloWorldRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/HelloWorld", ReplyAction = "*")]
        System.Threading.Tasks.Task<ITSApplication.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ITSApplication.ServiceReference1.HelloWorldRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class HelloWorldRequest
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "HelloWorld", Namespace = "http://tempuri.org/", Order = 0)]
        public ITSApplication.ServiceReference1.HelloWorldRequestBody Body;

        public HelloWorldRequest()
        {
        }

        public HelloWorldRequest(ITSApplication.ServiceReference1.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        public HelloWorldRequestBody()
        {
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class HelloWorldResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "HelloWorldResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public ITSApplication.ServiceReference1.HelloWorldResponseBody Body;

        public HelloWorldResponse()
        {
        }

        public HelloWorldResponse(ITSApplication.ServiceReference1.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class HelloWorldResponseBody
    {
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string HelloWorldResult;

        public HelloWorldResponseBody()
        {
        }

        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageUploader1SoapChannel : ITSApplication.ServiceReference1.ImageUploader1Soap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageUploader1SoapClient : System.ServiceModel.ClientBase<ITSApplication.ServiceReference1.ImageUploader1Soap>, ITSApplication.ServiceReference1.ImageUploader1Soap
    {
        public ImageUploader1SoapClient()
        {
        }

        public ImageUploader1SoapClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ImageUploader1SoapClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ImageUploader1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ImageUploader1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ITSApplication.ServiceReference1.HelloWorldResponse ITSApplication.ServiceReference1.ImageUploader1Soap.HelloWorld(ITSApplication.ServiceReference1.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }

        public string HelloWorld()
        {
            ITSApplication.ServiceReference1.HelloWorldRequest inValue = new ITSApplication.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ITSApplication.ServiceReference1.HelloWorldRequestBody();
            ITSApplication.ServiceReference1.HelloWorldResponse retVal = ((ITSApplication.ServiceReference1.ImageUploader1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ITSApplication.ServiceReference1.HelloWorldResponse> ITSApplication.ServiceReference1.ImageUploader1Soap.HelloWorldAsync(ITSApplication.ServiceReference1.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }

        public System.Threading.Tasks.Task<ITSApplication.ServiceReference1.HelloWorldResponse> HelloWorldAsync()
        {
            ITSApplication.ServiceReference1.HelloWorldRequest inValue = new ITSApplication.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ITSApplication.ServiceReference1.HelloWorldRequestBody();
            return ((ITSApplication.ServiceReference1.ImageUploader1Soap)(this)).HelloWorldAsync(inValue);
        }
    }
}